wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    code_path: code/examples/voxceleb/v2/wespeaker/bin/train.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1655391485
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      4: 3.9.12
      5: 0.12.17
      8:
      - 5
checkpoint:
  desc: null
  value: exp/ResNet34-TSTP-emb256-fbank80-num_frms200-aug0.6-spTrue-saFalse-ArcMargin-SGD-epoch150/models/avg_model.pt
data_type:
  desc: null
  value: shard
dataloader_args:
  desc: null
  value:
    batch_size: 192
    drop_last: true
    num_workers: 4
    pin_memory: false
    prefetch_factor: 4
dataset_args:
  desc: null
  value:
    aug_prob: 0.6
    fbank_args:
      dither: 1.0
      frame_length: 25
      frame_shift: 10
      num_mel_bins: 80
    num_frms: 200
    shuffle: true
    shuffle_args:
      shuffle_size: 2500
    spec_aug: false
    spec_aug_args:
      max_f: 8
      max_t: 10
      num_f_mask: 1
      num_t_mask: 1
      prob: 0.6
    speed_perturb: true
exp_dir:
  desc: null
  value: exp/ResNet34-TSTP-emb256-fbank80-num_frms200-aug0.6-spTrue-saFalse-ArcMargin-SGD-epoch150_rev-data
gpus:
  desc: null
  value:
  - 0
  - 1
  - 2
  - 3
log_batch_interval:
  desc: null
  value: 100
loss:
  desc: null
  value: CrossEntropyLoss
loss_args:
  desc: null
  value: {}
margin_scheduler:
  desc: null
  value: MarginScheduler
margin_update:
  desc: null
  value:
    final_margin: 0.2
    fix_start_epoch: 40
    increase_start_epoch: 20
    increase_type: exp
    initial_margin: 0.0
    update_margin: true
model:
  desc: null
  value: ResNet34
model_args:
  desc: null
  value:
    embed_dim: 256
    feat_dim: 80
    pooling_func: TSTP
model_init:
  desc: null
  value: exp/ResNet101-TSTP-emb256-fbank80-num_frms200-aug0.6-spTrue-saFalse-ArcMargin-SGD-epoch150/models/model_45.pt
noise_data:
  desc: null
  value: data/musan/lmdb
num_avg:
  desc: null
  value: 10
num_epochs:
  desc: null
  value: 150
optimizer:
  desc: null
  value: SGD
optimizer_args:
  desc: null
  value:
    momentum: 0.9
    nesterov: true
    weight_decay: 0.0001
projection_args:
  desc: null
  value:
    easy_margin: false
    project_type: arc_margin
    scale: 32.0
reverb_data:
  desc: null
  value: data/rirs/lmdb
save_epoch_interval:
  desc: null
  value: 5
scheduler:
  desc: null
  value: ExponentialDecrease
scheduler_args:
  desc: null
  value:
    final_lr: 5.0e-05
    initial_lr: 0.1
    warm_up_epoch: 6
seed:
  desc: null
  value: 42
train_data:
  desc: null
  value: data/train/shard.list
train_label:
  desc: null
  value: data/train/utt2spk
